from django.urls import path

from . import views

urlpatterns = [
    path('auth/register', views.auth_register),
    path('auth/login', views.auth_login),
    path('auth/logout', views.auth_logout),
    path('admin/auth/login', views.admin_auth_login),
    path('admin/auth/logout', views.admin_auth_logout),
    path('admin/auth/me', views.admin_auth_me),
    path('users/me', views.users_me),
    path('users/me/profile', views.users_me_profile_update),
    path('admin/dashboard/overview', views.admin_dashboard_overview),
    path('admin/moderation/posts', views.admin_posts),
    path('admin/moderation/posts/<int:post_id>', views.admin_post_detail),
    path('admin/moderation/posts/<int:post_id>/review', views.admin_post_review),
    path('admin/moderation/comments', views.admin_comments),
    path('admin/moderation/comments/<int:comment_id>/hide', views.admin_comment_hide),
    path('admin/moderation/comments/<int:comment_id>/restore', views.admin_comment_restore),
    path('admin/moderation/comments/<int:comment_id>', views.admin_comment_delete),
    path('admin/users', views.admin_users),
    path('admin/users/<int:user_id>/roles', views.admin_user_roles),
    path('admin/audit/logs', views.admin_audit_logs),
    path('community/bootstrap', views.community_bootstrap),
    path('community/recommend', views.community_recommend),
    path('community/recommend/status', views.community_recommend_status),
    path('community/search', views.community_search),
    path('community/posts', views.posts_create),
    path('community/posts/<int:post_id>', views.posts_update),
    path('community/posts/<int:post_id>/comments', views.comments_create),
    path('community/posts/<int:post_id>/like', views.post_like_toggle),
    path('community/posts/<int:post_id>/favorite', views.post_favorite_toggle),
    path('community/authors/<int:author_id>/follow', views.author_follow_toggle),
    path('community/comments/<int:comment_id>/like', views.comment_like_toggle),
    path('community/comments/<int:comment_id>', views.comment_delete),
]
